# Generated by Django 5.1.7 on 2025-12-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=50)),
                ("expirationDate", models.DateTimeField()),
                ("barcode", models.CharField(max_length=300)),
            ],
        ),
    ]
