# Generated by Django 5.1.7 on 2025-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProductsApp", "0002_remove_product_expirationdate_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(max_length=300),
        ),
    ]
