# Generated by Django 5.1.7 on 2025-12-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProductsApp", "0003_alter_product_barcode"),
        ("UsersApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user_id",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="UsersApp.user",
            ),
        ),
    ]
