# Generated by Django 5.1.7 on 2025-12-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProductsApp", "0004_product_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user_id",
            new_name="user",
        ),
    ]
