# Generated by Django 5.1.7 on 2026-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0003_user_role_alter_user_email_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
