# Generated by Django 5.1.7 on 2026-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
